export const SIGNALS = [
  {
    id: 1,
    title: 'Geberit files patent for AI-powered leak-detection smart valve',
    source: 'EPO Patent Registry',
    type: 'Competitor',
    timeAgo: '2h ago',
    impact: 92,
    recommendation: 'BUILD',
    confidence: 87,
    summary: 'Direct competitor moves into connected-water category. Patent covers ML-based flow anomaly detection, potential category-defining play.',
    reasoning: [
      'Smart-water is projected to hit 4.2B EUR by 2028 (CAGR 19%)',
      'Viega already has press-fit infrastructure to bolt sensors onto',
      'First-mover lock-in risk if we wait more than 6 months',
    ],
    debate: [
      { persona: 'david', message: 'This is exactly the signal we have been waiting for. If Geberit locks down AI leak-detection IP, we are fighting uphill for a decade. We need a counter-patent filed in Q2.' },
      { persona: 'josef', message: 'Patents do not sell fittings. Plumbers trust what they have installed for 20 years. Are we sure end-customers actually want another app on their phone?' },
      { persona: 'david', message: 'Insurance companies are pushing this, Josef. State Farm already offers 10% discounts for homes with smart leak detection. This is not about plumbers, it is about the specifier.' },
      { persona: 'steffen', message: 'Agree with David, but only if installation stays under 4 minutes per valve. If it needs a laptop and pairing ritual, installers will reject it on site.' },
      { persona: 'josef', message: 'Fine, but the sensor must not compromise the mechanical seal. That is non-negotiable.' },
    ],
    personaVotes: { david: 'BUILD', josef: 'INVEST', steffen: 'BUILD' },
  },
  {
    id: 2,
    title: 'EU regulation: All new buildings must be hydrogen-ready by 2028',
    source: 'EU Official Journal',
    type: 'Regulation',
    timeAgo: '5h ago',
    impact: 88,
    recommendation: 'INVEST',
    confidence: 91,
    summary: 'Directive 2026/114 mandates H2-compatible piping in all new residential construction across EU-27. Affects brass, seals, and press fittings.',
    reasoning: [
      'Regulatory floor, not optional, EU-wide',
      'Existing brass formulations degrade under H2 embrittlement',
      '3-year runway for R&D before enforcement',
    ],
    debate: [
      { persona: 'josef', message: 'Finally a signal that plays to our strengths. Material science is our moat. We should allocate R&D to hydrogen-grade alloys immediately.' },
      { persona: 'david', message: 'Agreed, but we should also embed digital H2 compatibility certificates in every product. QR codes installers scan for compliance audits.' },
      { persona: 'steffen', message: 'The real question: can we keep the same press-fit tooling? If installers need new jaws, we lose the whole installed base of Pressgun users.' },
      { persona: 'josef', message: 'Tool-compatibility must be requirement number one. I would rather delay launch than fragment our tooling ecosystem.' },
    ],
    personaVotes: { david: 'INVEST', josef: 'INVEST', steffen: 'INVEST' },
  },
  {
    id: 3,
    title: 'TikTok trend: #PlumberLife DIY smart-shower hacks hit 240M views',
    source: 'Social Listening',
    type: 'Market Buzz',
    timeAgo: '1d ago',
    impact: 34,
    recommendation: 'IGNORE',
    confidence: 79,
    summary: 'Viral consumer trend of DIY shower modifications. High visibility, low strategic relevance to B2B installation market.',
    reasoning: [
      'Zero overlap with specifier / wholesaler channel',
      'DIY segment below 3% of Viega revenue',
      'Trend half-life typically under 90 days',
    ],
    debate: [
      { persona: 'david', message: 'There might be a brand play here. Gen Z plumbing apprentices are on TikTok. Cheap marketing win.' },
      { persona: 'josef', message: 'Our customers are master plumbers and planning engineers. Chasing hashtags dilutes the brand. Hard pass.' },
      { persona: 'steffen', message: 'I side with Josef. Every hour we spend on this is an hour not spent on jobsite productivity. Ignore.' },
    ],
    personaVotes: { david: 'INVEST', josef: 'IGNORE', steffen: 'IGNORE' },
  },
  {
    id: 4,
    title: 'Grohe acquires smart-home startup Orvibo-Water for 120M EUR',
    source: 'Reuters',
    type: 'M&A',
    timeAgo: '1d ago',
    impact: 81,
    recommendation: 'BUILD',
    confidence: 74,
    summary: 'Grohe (LIXIL Group) absorbs app-layer and cloud backend for connected bathroom. Signals accelerated consolidation in smart-water space.',
    reasoning: [
      'Second major competitor move this quarter',
      'Build-vs-buy window narrowing',
      'Viega lacks consumer-app capability in-house',
    ],
    debate: [
      { persona: 'david', message: 'Two competitors, two moves, three months. The window is closing. We either acquire a similar player or we build, but doing nothing is the worst option.' },
      { persona: 'josef', message: 'Acquisitions fail 70% of the time. Let us build what fits our DNA rather than inherit someone else tech debt.' },
      { persona: 'steffen', message: 'Build-path only works if the output integrates with our existing tooling. I have seen too many smart products that slowed installers down.' },
    ],
    personaVotes: { david: 'BUILD', josef: 'BUILD', steffen: 'INVEST' },
  },
  {
    id: 5,
    title: 'Construction labor shortage drives 30% demand surge for press-fit systems',
    source: 'Handelsblatt',
    type: 'Market Trend',
    timeAgo: '2d ago',
    impact: 76,
    recommendation: 'BUILD',
    confidence: 83,
    summary: 'DACH region master-plumber shortage accelerates shift from soldering to press-fit. Viega core strength, capacity expansion opportunity.',
    reasoning: [
      'Direct tailwind for existing product line',
      'Press-fit margins 2.3x vs. traditional',
      'Competitor supply lead-times currently 8+ weeks',
    ],
    debate: [
      { persona: 'steffen', message: 'This is THE signal. Plumbers are begging for speed. We should expand Pressgun production and offer a 48-hour delivery guarantee in DACH.' },
      { persona: 'josef', message: 'Finally, a market that rewards what we already do best. Double down on capacity.' },
      { persona: 'david', message: 'Agreed, and let us instrument every Pressgun with usage telemetry. That data is gold for the next product cycle.' },
    ],
    personaVotes: { david: 'BUILD', josef: 'BUILD', steffen: 'BUILD' },
  },
  {
    id: 6,
    title: 'BIM integration becomes mandatory for public projects in Germany',
    source: 'BMWSB Announcement',
    type: 'Regulation',
    timeAgo: '3d ago',
    impact: 69,
    recommendation: 'INVEST',
    confidence: 72,
    summary: 'Federal mandate requires BIM-ready component libraries for all public construction bids from 2027. Affects product data strategy.',
    reasoning: [
      'Specifier workflow increasingly digital-first',
      'Viega BIM library currently behind Uponor',
      'Low-risk, high-leverage R&D investment',
    ],
    debate: [
      { persona: 'david', message: 'Our BIM objects are outdated. This is low-hanging fruit, 2 quarters of dev work and we are at parity.' },
      { persona: 'steffen', message: 'As long as it does not distract from physical product. BIM wins specs, it does not move boxes.' },
      { persona: 'josef', message: 'Fine, but let us not pretend this is strategic. It is table stakes.' },
    ],
    personaVotes: { david: 'INVEST', josef: 'INVEST', steffen: 'INVEST' },
  },
];
